const fs = require("fs").promises;
const path = require("path");

function pascalCase(word) {
  const words = word.match(/[a-z]+/gi);
  if (!words) {
    return "";
  }
  return words
    .map(function (word) {
      return word.charAt(0).toUpperCase() + word.substr(1).toLowerCase();
    })
    .join("");
}

const iconsDir = path.join(__dirname, "../src/icons/icons");
const processFile = async (file, data) => {
  file = path.join(iconsDir, file);
  if (path.extname(file) !== ".svg") {
    return;
  }
  const name = pascalCase(path.basename(file, ".svg"));
  const componentName = `BIconForge${name}`;

  const svg = await fs.readFile(file, "utf8");

  const content = svg
  // Remove <svg ...> and </svg>
    .replace(/<svg[^>]+>/i, "")
    .replace(/<\/svg>/i, "")
  // Remove whitespace between elements
    .replace(/>\s+</g, "><")
    .replace(/\n/g, "")
    .replace(/\r/g, "")
    .replace(/fill="[^"]*"/gm, "")
  // Fix broken stroke colors in some components
  // Might be fixed in 1.0.0-alpha3 release
    .replace(" stroke=\"#000\"", " stroke=\"currentColor\"")
  // Remove leading/trailing whitespace
    .trim();
  // Add to the iconsData object
  return {name: componentName, content};

};

const main = async () => {
  const today = new Date();
  const data = {
    created: today.toISOString(),
    icons: {}
  };

  // Read in the list of SVG Files
  const files = await fs.readdir(iconsDir);

  // Process the SVG Data for all files
  const results = await Promise.all(files.map(file => processFile(file, data)));

  data.icons = Object.fromEntries(
    results.map(e => [e.name, e.content])
  );

  let iconsFile =
   "/* DO NOT EDIT THIS FILE IT IS AUTO GENERATED */\nimport { VueConstructor } from 'vue'\n// @ts-ignore\nimport { makeIcon } from 'bootstrap-vue/src/icons/helpers/make-icon'; \n";
  for (const icon in data.icons) {
    iconsFile += `export const ${icon} = /*#__PURE__*/ makeIcon("${icon}",\`${data.icons[icon]}\`) \n`;
  }

  iconsFile += `\nexport const ForgeIcons = {
  install(Vue: VueConstructor) {\n`;

  for (const icon in data.icons) {
    iconsFile += `    Vue.component("${icon}",${icon}) \n`;
  }

  iconsFile += " } \n} \n export default ForgeIcons";

  await fs.writeFile(iconsDir + ".ts", iconsFile);
};
main();
